from __future__ import annotations


VOICE_CAPTURE_MODE = "fixed"
FIXED_CAPTURE_SECONDS = 5
MICROPHONE_DEVICE_INDEX = 15

VOICE_CHANNELS = 1
VOICE_SAMPLE_WIDTH_BYTES = 2

OLLAMA_BASE_URL = "http://127.0.0.1:11434"
OLLAMA_MODEL = "qwen3:8b"
OLLAMA_TIMEOUT_SECONDS = 30.0
OLLAMA_KEEP_ALIVE = "10m"
